language: node_js
node_js:
- 10
script:
- npm install
- npm run build
- chmod 600 ./pr_key.pem
- ssh-keyscan -H $front_host >> ~/.ssh/known_hosts
- scp -i ./pr_key.pem -r ./public/dist ubuntu@$front_host:/home/ubuntu/
branches:
  only:
  - cors
  - game
before_install:
- openssl aes-256-cbc -K $encrypted_6361ba71dc72_key -iv $encrypted_6361ba71dc72_iv
  -in pr_key.pem.enc -out ./pr_key.pem -d
