language: node_js
node_js:
- 10
script:
- npm install
- npm run build
- chmod 600 ./id_rsa
- ssh-keyscan -H $front_host >> ~/.ssh/known_hosts
- scp -i ./id_rsa -r ./public/dist root@$front_host:/home/ubuntu/
branches:
  only:
  - cors
before_install:
- openssl aes-256-cbc -K $encrypted_6361ba71dc72_key -iv $encrypted_6361ba71dc72_iv
  -in id_rsa.enc -out ./id_rsa -d
