language: node_js
node_js:
- 10
script:
- chmod 600 ./id_rsa
- ssh-keyscan -H 178.128.201.109 >> ~/.ssh/known_hosts
- scp -i ./id_rsa -r ./public/dist root@178.128.201.109:/home/ubuntu/
branches:
  only:
  - cors
before_install:
- openssl aes-256-cbc -K $encrypted_dfc380f56b41_key -iv $encrypted_dfc380f56b41_iv
  -in id_rsa.enc -out ./id_rsa -d
